# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0003_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bid',
            name='lot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lots.Lot'),
        ),
    ]
