# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0004_auto_20200721_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lots.Lot'),
        ),
    ]
