# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20200721_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
