# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auction_done',
        ),
        migrations.RemoveField(
            model_name='product',
            name='auction_time',
        ),
    ]
